port: ":8080"
logLevel: "debug"
salt: "secret"

db:
  host: "localhost"
  port: "5432"
  name: "postgres"
  user: "postgres"
  password: "postgres"

cache:
  host: "localhost"
  port: "6379"
  db: 1
  password: ""